### Implementação do Simplex Tableau

In [1]:
from Simplex import simplex
import numpy as np

In [2]:
c = [-1, -3, -5, 0, 0]
A = [[2, -5, 1,1,0],[1,4,0,0,1]]
b = [3,5]

simplex(c, A, b, verbose=True)

Iteração 1:
[[ 0 -1 -3 -5  0  0]
 [ 3  2 -5  1  1  0]
 [ 5  1  4  0  0  1]]
O pivô está na linha 1 e coluna 1 

Iteração 2:
[[ 1.5  0.  -5.5 -4.5  0.5  0. ]
 [ 1.5  1.  -2.5  0.5  0.5  0. ]
 [ 3.5  0.   6.5 -0.5 -0.5  1. ]]
O pivô está na linha 2 e coluna 2 

Iteração 3:
[[ 4.46153846  0.          0.         -4.92307692  0.07692308  0.84615385]
 [ 2.84615385  1.          0.          0.30769231  0.30769231  0.38461538]
 [ 0.53846154  0.          1.         -0.07692308 -0.07692308  0.15384615]]
O pivô está na linha 1 e coluna 3 



([[49.99999999999999, 16.0, 0.0, 0.0, 5.0, 7.0],
  [9.249999999999998, 3.25, 0.0, 1.0, 1.0, 1.25],
  [1.25, 0.25, 1.0, 0.0, 0.0, 0.25]],
 {'x2': 1.25, 'x3': 9.2499999999999982},
 -49.99999999999999)

In [3]:
c = [-4, -2, 5, 0, 0, 0]
A = [[-2,5,1,1,0,0,0],[1,4,-2,0,1,0,0],[3,-2,7,0,0,1,0]]
b = [3,-5,9]

simplex(c, A, b, verbose=True)[1:]

Iteração 1:
[[0, -4, -2, 5, 0, 0, 0] [3, -2, 5, 1, 1, 0, 0, 0]
 [-5, 1, 4, -2, 0, 1, 0, 0] [9, 3, -2, 7, 0, 0, 1, 0]]
O pivô está na linha 2 e coluna 1 

Iteração 2:
[[-20.0, 0.0, 14.0, -3.0, 0.0, 4.0, 0.0]
 [-7.0, 0.0, 13.0, -3.0, 1.0, 2.0, 0.0, 0.0]
 [-5.0, 1.0, 4.0, -2.0, 0.0, 1.0, 0.0, 0.0]
 [24.0, 0.0, -14.0, 13.0, 0.0, -3.0, 1.0, 0.0]]
O pivô está na linha 3 e coluna 3 



'Problema sem solução.'

In [9]:
c = [-4,-3, 0,0]
A = [[3,0,1,0], [1,2,0,1]]
b = [2,3]

simplex(c,A,b, verbose=True)[1:]

Iteração 1:
[[ 0 -4 -3  0  0]
 [ 2  3  0  1  0]
 [ 3  1  2  0  1]]
O pivô está na linha 1 e coluna 1 

Iteração 2:
[[ 2.66666667  0.         -3.          1.33333333  0.        ]
 [ 0.66666667  1.          0.          0.33333333  0.        ]
 [ 2.33333333  0.          2.         -0.33333333  1.        ]]
O pivô está na linha 2 e coluna 2 



({'x1': 0.66666666666666663, 'x2': 1.1666666666666667}, -6.166666666666666)